name: Check for Elementor Updates

on:
  schedule:
    - cron: '0 0 1,15 * *' # biweekly
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  check-version:
    uses: artkrsk/stub-package-workflows/.github/workflows/stub-check-updates.yml@165729a6013366aa155d252c39bcc204f5151dac # master
    with:
      primary_slug: elementor
      secondary_source: github-release
      secondary_repo: proelements/proelements
