name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  test:
    uses: artkrsk/stub-package-workflows/.github/workflows/stub-test.yml@165729a6013366aa155d252c39bcc204f5151dac # master
    with:
      stub_file: elementor-stubs.php
